name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Scan
    runs-on: [General]  # Changed from [General] to a standard runner
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: NPM Install
        run: npm install

      - name: Install Trivy
        run: |
          trivy fs . > trivyfs.txt

      - name: Docker build and push
        run: |
          docker build -t tic-tac-toe .
          docker tag tic-tac-toe jall1985/tic-tac-toe:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push jall1985/tic-tac-toe:latest
        env:
          DOCKER_CLI_ACI: 1

      - name: Image scan
        run: trivy image jall1985/tic-tac-toe:latest > trivyimage.txt

  deploy:
    name: Deploy to Kubernetes
    needs: build
    runs-on: [General]
    steps:
      - name: Docker pull image
        run: docker pull jall1985/tic-tac-toe:latest

      - name: Image scan
        run: trivy image jall1985/tic-tac-toe:latest > trivyimagedeploy.txt  

      - name: Deploy to container
        run: docker run -d --name game -p 3000:3000 jall1985/tic-tac-toe:latest

      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-service.yml

      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#jenkins-cicd'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


    
